sudo: required
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
  - $HOME/tika

before_install:
  - sudo pip install codecov
  - sudo apt-get install tesseract-ocr

install:
  - composer install

before_script:
  - \[ -f $HOME/tika/tika-app.jar \] || wget -O $HOME/tika/tika-app.jar http://mirrors.ibiblio.org/apache/tika/tika-app-1.11.jar
  - \[ -f $HOME/tika/tika-server.jar \] || wget -O $HOME/tika/tika-server.jar -nc http://mirrors.ibiblio.org/apache/tika/tika-server-1.11.jar
  - java -jar $HOME/tika/tika-server.jar 2> /dev/null &
  - sleep 10

after_success:
  - codecov

notifications:
  email:
    - contacto@davidmartinez.net