language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

addons:
  apt:
    packages:
    - tesseract-ocr

cache:
  directories:
  - $HOME/tika

install:
  - composer install

before_script:
  - wget -O $HOME/tika/tika-app.jar -nc http://mirrors.ibiblio.org/apache/tika/tika-app-1.11.jar
  - wget -O $HOME/tika/tika-server.jar -nc http://mirrors.ibiblio.org/apache/tika/tika-server-1.11.jar
  - java -jar $HOME/tika/tika-server.jar &
  - sleep 10

notifications:
  email:
    - contacto@davidmartinez.net