language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install

before_script:
  - wget -O /tmp/tika-server.jar http://www.eu.apache.org/dist/tika/tika-server-1.10.jar
  - java -jar /tmp/tika-server.jar

notifications:
  email:
    - contacto@davidmartinez.net